/* afhdlTheme.js — inline style tokens for AFHDL page components.
   All color values reference CSS custom properties so they respond
   correctly to both dark and light themes.                        */

export const afhdlTheme = {
  sectionTitle: {
    fontSize: "1.05rem",
    fontWeight: 700,
    color: "var(--afhdl-text)",
    margin: "1.4rem 0 0.45rem",
    letterSpacing: "-0.01em",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  body: {
    color: "var(--afhdl-muted)",
    fontSize: "0.93rem",
    lineHeight: 1.7,
    margin: "0.4rem 0",
  },
  welcomeBanner: {
    background:
      "linear-gradient(135deg, rgba(79,70,229,0.12), rgba(59,130,246,0.1))",
    border: "1px solid var(--afhdl-border-strong)",
    borderRadius: "14px",
    padding: "1rem 1.2rem",
    marginBottom: "0.5rem",
  },
  welcomeHeader: {
    display: "flex",
    alignItems: "center",
    gap: "0.8rem",
  },
  teacherBubble: {
    display: "flex",
    gap: "0.7rem",
    background: "var(--afhdl-accent-soft)",
    border: "1px solid var(--afhdl-border-strong)",
    borderRadius: "12px",
    padding: "0.85rem 1rem",
    margin: "0.4rem 0",
    alignItems: "flex-start",
  },
  teacherAvatar: {
    fontSize: "1.4rem",
    flexShrink: 0,
    lineHeight: 1,
    marginTop: "0.05rem",
  },
  teacherText: {
    color: "var(--afhdl-muted-strong)",
    fontSize: "0.86rem",
    lineHeight: 1.65,
  },
  teacherCallout: {
    background: "var(--afhdl-accent-soft)",
    border: "1px solid var(--afhdl-border-strong)",
    borderRadius: "12px",
    padding: "1rem",
    marginBottom: "1rem",
  },
  nextTipBtn: {
    background: "transparent",
    border: "1px solid var(--afhdl-border-strong)",
    borderRadius: "6px",
    color: "var(--afhdl-accent)",
    padding: "0.3rem 0.8rem",
    cursor: "pointer",
    fontSize: "0.76rem",
    transition: "all 0.2s",
  },
  card: {
    background: "var(--afhdl-surface)",
    backdropFilter: "blur(12px)",
    border: "1px solid var(--afhdl-border)",
    borderRadius: "16px",
    padding: "1.2rem",
    marginTop: "0.75rem",
    boxShadow: "var(--afhdl-shadow)",
  },
  conceptBox: (color) => ({
    background: `${color}12`,
    border: `1px solid ${color}55`,
    borderRadius: "16px",
    padding: "1rem 1.1rem",
  }),
  formula: {
    background: "var(--afhdl-surface-soft)",
    border: "1px solid var(--afhdl-border-strong)",
    borderRadius: "12px",
    padding: "1rem",
    fontFamily: "'Fira Code', monospace",
    fontSize: "0.84rem",
    color: "var(--afhdl-accent)",
    margin: "0.75rem 0",
    lineHeight: 1.7,
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
  },
  formulaBox: (color) => ({
    background: `${color}10`,
    border: `1px solid ${color}44`,
    borderRadius: "10px",
    padding: "0.7rem",
  }),
  codeBlock: {
    background: "var(--afhdl-surface-strong)",
    border: "1px solid var(--afhdl-border)",
    borderRadius: "12px",
    padding: "1rem",
    overflowX: "auto",
    position: "relative",
  },
  resultBanner: {
    background:
      "linear-gradient(135deg, rgba(79,70,229,0.1), rgba(59,130,246,0.08))",
    border: "1px solid var(--afhdl-border-strong)",
    borderRadius: "16px",
    padding: "1rem 1.2rem",
    margin: "1rem 0",
    backdropFilter: "blur(8px)",
  },
  tabPanel: {
    background: "var(--afhdl-surface)",
    backdropFilter: "blur(12px)",
    border: "1px solid var(--afhdl-border)",
    borderRadius: "0 16px 16px 16px",
    padding: "1.2rem",
    minHeight: "220px",
  },
  note: (color) => ({
    background: `${color}12`,
    borderLeft: `4px solid ${color}`,
    borderRadius: "8px",
    padding: "0.85rem 1rem",
    fontSize: "0.84rem",
    color: "var(--afhdl-muted-strong)",
    lineHeight: 1.65,
    margin: "0.75rem 0",
  }),
  signalBox: (color) => ({
    background: `${color}0a`,
    border: `1px solid ${color}33`,
    borderRadius: "12px",
    padding: "0.75rem",
    textAlign: "center",
    transition: "transform 0.2s ease",
  }),
  conceptCard: (color) => ({
    background: "var(--afhdl-surface)",
    border: "1px solid var(--afhdl-border)",
    borderTop: `4px solid ${color}`,
    borderRadius: "12px",
    padding: "1rem",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
  }),
  analogyCard: (color) => ({
    background: `${color}10`,
    border: `1px solid ${color}2d`,
    borderRadius: "10px",
    padding: "0.75rem",
    textAlign: "center",
  }),
  analogyBox: {
    background: "rgba(245, 158, 11, 0.1)",
    border: "1px solid rgba(245, 158, 11, 0.28)",
    borderRadius: "10px",
    padding: "0.85rem 1rem",
    margin: "0.75rem 0",
  },
  stepBox: {
    display: "flex",
    gap: "0.75rem",
    alignItems: "flex-start",
    margin: "0.55rem 0",
    padding: "0.65rem 0.9rem",
    background: "var(--afhdl-surface-soft)",
    borderRadius: "10px",
    border: "1px solid var(--afhdl-border)",
  },
  stepNumber: {
    background: "var(--afhdl-accent-soft)",
    color: "var(--afhdl-accent)",
    borderRadius: "6px",
    padding: "0.15rem 0.5rem",
    fontSize: "0.7rem",
    fontWeight: 800,
    whiteSpace: "nowrap",
    flexShrink: 0,
    marginTop: "0.1rem",
  },
  stepContent: {
    color: "var(--afhdl-muted-strong)",
    fontSize: "0.86rem",
    lineHeight: 1.65,
  },
  inputGroup: {
    background: "var(--afhdl-surface)",
    border: "1px solid var(--afhdl-border)",
    borderRadius: "12px",
    padding: "0.85rem 1rem",
  },
  overflowBadge: {
    background: "rgba(245, 158, 11, 0.14)",
    border: "1px solid #f59e0b",
    borderRadius: "6px",
    padding: "2px 8px",
    fontSize: "0.75rem",
    color: "#d97706",
    fontWeight: 600,
  },
  bitBtn: (bit, color) => ({
    width: "36px",
    height: "36px",
    borderRadius: "8px",
    border: `2px solid ${bit === "1" ? color : "var(--afhdl-border)"}`,
    background: bit === "1" ? `${color}20` : "var(--afhdl-surface-soft)",
    color: bit === "1" ? color : "var(--afhdl-muted)",
    fontWeight: 800,
    fontSize: "1rem",
    cursor: "pointer",
    transition: "all 0.14s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "monospace",
  }),
  cinBtn: (active) => ({
    padding: "0.42rem 1rem",
    borderRadius: "8px",
    border: `2px solid ${active ? "#f59e0b" : "rgba(245, 158, 11, 0.24)"}`,
    background: active ? "rgba(245, 158, 11, 0.14)" : "var(--afhdl-surface)",
    color: active ? "#d97706" : "var(--afhdl-muted)",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: "0.82rem",
    transition: "all 0.2s",
  }),
  tabBtn: (active, color) => ({
    padding: "0.55rem 1.15rem",
    borderRadius: "10px 10px 0 0",
    border: "none",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "0.875rem",
    background: active ? color : "transparent",
    color: active ? "#ffffff" : "var(--afhdl-muted)",
    transition: "all 0.2s ease",
    borderBottom: active ? "none" : "1px solid var(--afhdl-border)",
  }),
  tabSectionTitle: (color) => ({
    fontWeight: 800,
    color,
    marginBottom: "0.6rem",
    fontSize: "0.96rem",
  }),
  /* ── Table row styles using CSS vars ─── */
  tableHeader: {
    display: "grid",
    background: "var(--afhdl-table-header-bg)",
    borderRadius: "6px",
    padding: "0.32rem 0.5rem",
    fontSize: "0.72rem",
    fontWeight: 700,
    color: "#a5b4fc",
    textAlign: "center",
  },
  tableRow: {
    display: "grid",
    background: "var(--afhdl-table-row-bg)",
    borderRadius: "4px",
    padding: "0.28rem 0.5rem",
    fontSize: "0.8rem",
    textAlign: "center",
    color: "var(--afhdl-text)",
  },
  interactiveRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: "var(--afhdl-interactive-bg)",
    borderRadius: "6px",
    padding: "0.38rem 0.7rem",
    border: "1px solid var(--afhdl-border)",
  },
};
